/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TaskApp;


public class App {
   

    public static void main(String[] args) {
       

        
        
        
    }

   
}
